[package]
name = "moon_lol"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = { version = "0.16.0", features = ["dds", "bevy_picking", "serialize"] }
vleue_navigator = { version = "0.12", features = ["detailed-layers"] }
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = { version = "0.4", features = ["serde"] }
bitflags = "2.9.1"
thiserror = "2.0.12"
texpresso = "2.0.2"
image = "0.25.6"
zstd = "0.13.3"
twox-hash = "2.1.1"
ddsfile = "0.5.2"
bevy_egui = "0.35.1"
half = "2.6.0"
binrw = "0.15.0"
rand = "0.9.2"
serde = "1.0.219"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
bincode = "1.3"
heck = "0.5.0"
