[package]
name = "lol_config"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
league_core.workspace = true
league_utils.workspace = true
league_file.workspace = true
league_property.workspace = true
lol_core.workspace = true
serde.workspace = true
