[package]
name = "league_property"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
binrw.workspace = true
heck.workspace = true
league_utils.workspace = true
league_core.workspace = true
serde.workspace = true
thiserror.workspace = true
rayon = "1.10"
